name: Build-git-lfs
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        # https://github.com/actions/checkout#Fetch-all-history-for-all-tags-and-branches
        with:
          fetch-depth: 0 #Fetch all history for all tags and branches

      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          check-latest: true
          go-version: '1.20' # https://go.dev/dl
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Clone Repositories
        run: |
          ver="$(grep -v '^#' version)" || ver=main
          git clone --depth=1 https://github.com/git-lfs/git-lfs -b $ver gitlfs

      - name: Build and Push
        run: bash ./build
